### PR TITLE
Show Timestamp for data in results

### PR DESCRIPTION
**Pull request by zottelchin**
Display Timestamp from Rest-Response-Data so people are not confused if the data shown is different to the press release of their local government.
Unfortunately I couldn't test it, because I couldn't figure out where to get the RKI-API-Key from.

PS. very cool project

### CODE REVIEW

**Comment by zottelchin** [comment]
Thanks for authorizing this PR. In the Preview there is no Date displayed though i'll have to look into it further.

**Comment by jonicious** [comment]
@zottelchin Thanks for the PR! Just a little typo, I think. It needs to be `last_update`, not `lastUpdate`

**Comment by zottelchin** [comment]
Was a typo 😅 it needed to be `lastUpdated` instead of `lastUpdate`. It's not `last_upadte` because you rename it to `lastUpdated` in [src/services/API.js:31](https://github.com/sebastianruehmann/hotspotornot/blob/d5844165e801bbeb1c5355ba8d56e2fdb4dee7fc/src/services/Api.js#L31)

**Comment by jonicious** [comment]
Thanks, @zottelchin! :)

**Pull request merged**
